import {u16,u32,hex} from './rof.mjs';
import {odbEnd,associations,stringAt,elementInfo,parameters} from './odb.mjs';
import {prism,combine,transformed} from './solid.mjs';
export const CLASSES={wall:'8245654faf33524eabfcc35d46765ec4',window:'a061f1934e4cf74da1004fd0e8c4f1e1',object:'c3ceefdbbf1b6748b8b3c4f7c859df61',vrd:'0d9d7c5f4ba84042a67df1458abafd0e',lib:'3da3fc2b38bde349bf6d52ac8b850b9f'};
const FLOOR='0312b67984ae884da9c620ead705e0bc',WFLOOR='fa4c2e430499ca45a76b1b944ffc4041',PARENT='e67943c5d0af9a4b9887af5baeeccf84',VRD='67e6e5e67795ca41bf4ada75b917513f';
const one=(a,t)=>{const ids=a.get(t);if(ids?.length!==1)throw Error('関連する部材を一意に確認できません');return ids[0];};
function values(b,p,n){if(p+n*8>odbEnd(b))throw Error('部材寸法の範囲が不正です');const v=new DataView(b.buffer,b.byteOffset,b.byteLength),out=Array.from({length:n},(_,i)=>v.getFloat64(p+i*8,true));if(out.some(x=>!Number.isFinite(x)||Math.abs(x)>1e7))throw Error('部材寸法が不正です');return out;}
function library(r,records,a){const id=one(a,r.cls===CLASSES.window?'461c2f67f364f5418a4affdfd86bcbfd':'3e459f182eea384eafe9660d1d25afc6'),lib=records.get(id);if(lib?.cls!==CLASSES.lib)throw Error('部品ライブラリ参照が不正です');const link=associations(lib.data),param=records.get(one(link,'588778494a52594789accec113bc37f1'));if(!param)throw Error('部品寸法設定が見つかりません');return {library:stringAt(lib.data,85).text,main:hex(lib.data.subarray(51,67)),revision:hex(lib.data.subarray(67,83)),params:parameters(param.data)};}
function polygon(b,p){const end=odbEnd(b);if(hex(b.subarray(p,p+2))!=='0201'||u16(b,p+7)!==31)throw Error('壁輪郭の形式が不正です');const limit=p+6+u32(b,p+2),n=u32(b,p+41),arcs=u32(b,p+45),nc=u32(b,p+49);if(limit>end||n>100000||arcs||nc>1||n&&n<4)throw Error('曲線・複数輪郭の壁は未対応です');if(!n)return {flat:[],next:limit};const ep=p+53+(n+1)*16;if(ep+8>limit||u32(b,ep)!==0||u32(b,ep+4)!==n)throw Error('壁輪郭の頂点数が一致しません');const coords=values(b,p+69,n*2);if(Math.hypot(coords[0]-coords.at(-2),coords[1]-coords.at(-1))>1e-7)throw Error('壁の輪郭が閉じていません');return {flat:coords.slice(0,-2),next:limit};}
function trimX(flat,bound,less){const pts=[];for(let i=0;i<flat.length;i+=2)pts.push(flat.slice(i,i+2));const out=[];for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length],inside=p=>less?p[0]<=bound+1e-9:p[0]>=bound-1e-9;if(inside(a))out.push(a);if(inside(a)!==inside(b))out.push([bound,a[1]+(b[1]-a[1])*(bound-a[0])/(b[0]-a[0])]);}return out.flat();}
export function wallGeometry(w,openings=[]){const zs=[w.base,w.base+w.height,...openings.flatMap(o=>[Math.max(w.base,o.bottom),Math.min(w.base+w.height,o.bottom+o.height)])].filter(z=>z>=w.base&&z<=w.base+w.height).sort((a,b)=>a-b),unique=[...new Set(zs)],shapes=[];let min=Infinity,max=-Infinity;for(let i=0;i<w.footprint.length;i+=2){min=Math.min(min,w.footprint[i]);max=Math.max(max,w.footprint[i]);}
  for(let j=0;j<unique.length-1;j++){const low=unique[j],high=unique[j+1];if(high-low<1e-9)continue;const gaps=openings.filter(o=>o.bottom<(low+high)/2&&o.bottom+o.height>(low+high)/2).map(o=>[o.center-o.width/2,o.center+o.width/2]).sort((a,b)=>a[0]-b[0]);let first=min;for(const[a,b]of [...gaps,[max,max]]){const last=Math.min(a,max);if(last-first>1e-9){const poly=trimX(trimX(w.footprint,first,false),last,true);if(poly.length>=6)shapes.push(prism([poly],low,high));}first=Math.max(first,b);}}
  return transformed(combine(shapes),w.matrix);
}
export function readElements(records){const walls=new Map(),parts=[],failures=[],warnings=[];let excluded=0;
  for(const r of records.values())if(r.cls===CLASSES.wall){try{const a=associations(r.data);if(!a.has(FLOOR))continue;const info=elementInfo(r.data,r.cls,'wall'),p=info.after,b=r.data,[x,y,ex,ey]=values(b,p,4),length=Math.hypot(ex-x,ey-y),thickness=values(b,p+77,1)[0],height=values(b,p+153,1)[0],base=values(b,p+161,1)[0];if(length<1e-8||thickness<=0||height<=0||Math.abs(values(b,p+85,1)[0]-thickness)>1e-8||values(b,p+93,1)[0]!==0||b[p+76]!==1)throw Error('傾斜・曲線・特殊な壁は未対応です');const ux=(ex-x)/length,uy=(ey-y)/length,matrix=[ux,uy,0,x,uy,-ux,0,y,0,0,1,0];let footprint=[0,0,length,0,length,thickness,0,thickness],joined=false;
    if(a.has(VRD)){const cache=records.get(one(a,VRD));if(cache?.cls!==CLASSES.vrd||one(associations(cache.data),VRD)!==r.guid)throw Error('壁輪郭との関連が一致しません');const first=polygon(cache.data,46),second=polygon(cache.data,first.next);const chosen=second.flat.length?second:first;footprint=[];for(let i=0;i<chosen.flat.length;i+=2){const px=chosen.flat[i]-x,py=chosen.flat[i+1]-y;footprint.push(px*ux+py*uy,px*uy-py*ux);}joined=!!second.flat.length;}
    walls.set(r.guid,{id:r.guid,name:info.text,kind:'wall',floor:one(a,FLOOR),length,thickness,height,base,matrix,footprint,joined,openings:[]});
  }catch(e){failures.push({id:r.guid,message:e.message});}}
  for(const r of records.values())if([CLASSES.window,CLASSES.object].includes(r.cls)){try{const a=associations(r.data),window=r.cls===CLASSES.window,fl=window?WFLOOR:FLOOR;if(!a.has(fl))continue;const info=elementInfo(r.data,r.cls,window?'window':'object'),lib=library(r,records,a);if(/植栽|樹木|下草|観葉|落葉樹|常緑樹/.test(lib.library)){excluded++;continue;}
    const part={id:r.guid,name:info.text,kind:window?'window':'product',floor:one(a,fl),...lib};
    if(window){const w=walls.get(one(a,PARENT));if(!w)throw Error('窓の親壁を復元できません');const[width,height]=values(r.data,info.dimensions,2),center=values(r.data,info.after+24,1)[0],bottom=w.base+values(r.data,info.after+64,1)[0];if(width<=0||height<=0||Math.abs(width-lib.params.A)>1e-7||Math.abs(height-lib.params.B)>1e-7)throw Error('窓寸法が一致しません');Object.assign(part,{width,height,center,bottom,parent:w.id,matrix:[w.matrix[0],0,-w.matrix[1],w.matrix[3]+w.matrix[0]*center,w.matrix[4],0,-w.matrix[5],w.matrix[7]+w.matrix[4]*center,0,1,0,bottom]});part.params.WALL_THICKNESS=w.thickness;w.openings.push(part);
    }else{const[x,y,angle,z,A,B]=values(r.data,info.dimensions,6);part.params.A=A;part.params.B=B;const c=Math.cos(angle),s=Math.sin(angle);part.matrix=[c,-s,0,x,s,c,0,y,0,0,1,z];}
    parts.push(part);
  }catch(e){failures.push({id:r.guid,message:e.message});}}
  const objects=[];for(const w of walls.values()){try{const g=wallGeometry(w,w.openings);objects.push({...w,positions:new Float64Array(g.positions),indices:new Uint32Array(g.indices),matrix:undefined,footprint:undefined,openings:undefined});}catch(e){failures.push({id:w.id,message:e.message});}}
  warnings.push('壁は保存された基本高さで表示。屋根による上端トリム・ソリッド演算は未反映です。');
  return{objects,parts,failures,warnings,excluded};
}
