import earcut from '../vendor/earcut.js';
export const identity=()=>[1,0,0,0,0,1,0,0,0,0,1,0];
export function multiply(a,b){const r=[];for(let i=0;i<3;i++){for(let j=0;j<3;j++)r.push(a[i*4]*b[j]+a[i*4+1]*b[4+j]+a[i*4+2]*b[8+j]);r.push(a[i*4]*b[3]+a[i*4+1]*b[7]+a[i*4+2]*b[11]+a[i*4+3]);}return r;}
export const transform=(p,m)=>[0,1,2].map(i=>m[i*4]*p[0]+m[i*4+1]*p[1]+m[i*4+2]*p[2]+m[i*4+3]);
export function combine(shapes){const positions=[],indices=[];for(const s of shapes){const n=positions.length/3;for(const p of s.positions)positions.push(p);for(const i of s.indices)indices.push(i+n);}return{positions,indices};}
export function transformed(g,m){const det=m[0]*(m[5]*m[10]-m[6]*m[9])-m[1]*(m[4]*m[10]-m[6]*m[8])+m[2]*(m[4]*m[9]-m[5]*m[8]);return{positions:g.positions.flatMap((_,i,ar)=>i%3?[]:transform(ar.slice(i,i+3),m)),indices:det<0?g.indices.flatMap((_,i,a)=>i%3?[]:[a[i+2],a[i+1],a[i]]):g.indices};}
export function prism(rings,z0,z1){const flat=[],holes=[],indices=[],positions=[];for(const ring of rings){if(flat.length)holes.push(flat.length/2);flat.push(...ring);}const n=flat.length/2,t=earcut(flat,holes,2);if(!t.length)throw Error('輪郭の面分割に失敗しました');for(const z of[z0,z1])for(let i=0;i<n;i++)positions.push(flat[i*2],flat[i*2+1],z);for(let i=0;i<t.length;i+=3)indices.push(t[i+2],t[i+1],t[i],t[i]+n,t[i+1]+n,t[i+2]+n);let offset=0;for(const ring of rings){const k=ring.length/2;let area=0;for(let i=0;i<k;i++){const j=(i+1)%k;area+=ring[2*i]*ring[2*j+1]-ring[2*j]*ring[2*i+1];}for(let i=0;i<k;i++){const a=offset+i,b=offset+(i+1)%k;const face=[a,b,b+n,a,b+n,a+n];if((area<0)!==(offset>0))face.reverse();indices.push(...face);}offset+=k;}if(z1<z0)for(let i=0;i<indices.length;i+=3)[indices[i],indices[i+2]]=[indices[i+2],indices[i]];return{positions,indices};}
export const box=(x,y,z)=>prism([[0,0,x,0,x,y,0,y]],0,z);
export function round(height,r0,r1=r0,segments=24){const positions=[],indices=[];for(let j=0;j<2;j++)for(let i=0;i<segments;i++){const a=i*2*Math.PI/segments,r=j?r1:r0;positions.push(r*Math.cos(a),r*Math.sin(a),j*height);}positions.push(0,0,0,0,0,height);for(let i=0;i<segments;i++){let k=(i+1)%segments;indices.push(i,k,k+segments,i,k+segments,i+segments,2*segments,k,i,2*segments+1,i+segments,k+segments);}return{positions,indices};}
// Clip closed triangle meshes against a half-space and cap the resulting boundary.
export function clip(g,plane){const positions=[],indices=[],boundary=[];const distance=p=>p[0]*plane[0]+p[1]*plane[1]+p[2]*plane[2]-plane[3];const append=poly=>{const n=positions.length/3;for(const p of poly)positions.push(...p);for(let i=1;i<poly.length-1;i++)indices.push(n,n+i,n+i+1);};
  for(let t=0;t<g.indices.length;t+=3){const poly=g.indices.slice(t,t+3).map(i=>g.positions.slice(i*3,i*3+3)),out=[],cuts=[];for(let i=0;i<3;i++){const a=poly[i],b=poly[(i+1)%3],da=distance(a),db=distance(b),ia=da<=1e-9,ib=db<=1e-9;if(ia)out.push(a);if(ia!==ib){const p=a.map((v,j)=>v+(b[j]-v)*da/(da-db));out.push(p);cuts.push(p);}}if(out.length>=3)append(out);if(cuts.length===2&&Math.hypot(...cuts[0].map((x,i)=>x-cuts[1][i]))>1e-8)boundary.push(cuts);}
  const remaining=boundary.slice();while(remaining.length){const edge=remaining.pop(),ring=[edge[0],edge[1]];let closed=false;for(let j=0;j<=boundary.length;j++){const last=ring.at(-1),idx=remaining.findIndex(e=>e.some(p=>Math.hypot(...p.map((x,i)=>x-last[i]))<1e-7));if(idx<0)break;const e=remaining.splice(idx,1)[0],p=Math.hypot(...e[0].map((x,i)=>x-last[i]))<1e-7?e[1]:e[0];if(Math.hypot(...p.map((x,i)=>x-ring[0][i]))<1e-7){closed=true;break;}ring.push(p);}if(closed&&ring.length>=3){const drop=plane.slice(0,3).map(Math.abs).indexOf(Math.max(...plane.slice(0,3).map(Math.abs))),axes=[0,1,2].filter(i=>i!==drop),flat=ring.flatMap(p=>axes.map(i=>p[i])),tris=earcut(flat,[],2),n=positions.length/3;for(const p of ring)positions.push(...p);indices.push(...tris.map(i=>i+n));}}
  // The outward normal of a cap points towards the discarded half-space.
  for(let t=0;t<indices.length;t+=3){const ids=indices.slice(t,t+3),ps=ids.map(i=>positions.slice(i*3,i*3+3));if(ps.every(p=>Math.abs(distance(p))<1e-7)){const a=ps[1].map((x,i)=>x-ps[0][i]),b=ps[2].map((x,i)=>x-ps[0][i]),normal=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];if(normal.reduce((s,x,i)=>s+x*plane[i],0)<0)[indices[t],indices[t+2]]=[indices[t+2],indices[t]];}}
  return{positions,indices};}
